---
- name: Deploy Spring Boot Application
  hosts: seed-hosts
  vars:
    ci_cd_namespace: puckboard-hs-ci-cd
    dev_namespace: puckboard-hs-dev
    test_namespace: puckboard-hs-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
